FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY predict_server.py .
COPY model.cbm .
COPY stats.json .

EXPOSE 5050

CMD ["python", "predict_server.py"]
